import { UPSTREAM_PROVIDER_KEY } from '../payment/core/constants';

export const GATEWAY_PROVIDER = {
	XUNHUPAY: UPSTREAM_PROVIDER_KEY.XUNHUPAY,
	ALIPAY: UPSTREAM_PROVIDER_KEY.ALIPAY,
	WXPAY: UPSTREAM_PROVIDER_KEY.WXPAY,
	STRIPE: UPSTREAM_PROVIDER_KEY.STRIPE,
	GENERIC: UPSTREAM_PROVIDER_KEY.GENERIC,
} as const;

export type GatewayProvider = (typeof GATEWAY_PROVIDER)[keyof typeof GATEWAY_PROVIDER];

export const GATEWAY_RESULT_CODE = {
	ACCEPTED: 'ACCEPTED',
	PROVIDER_NOT_CONFIGURED: 'PROVIDER_NOT_CONFIGURED',
	INVALID_NOTIFICATION: 'INVALID_NOTIFICATION',
	ORDER_NOT_FOUND: 'ORDER_NOT_FOUND',
	ORDER_MISMATCH: 'ORDER_MISMATCH',
} as const;

export const GATEWAY_PROVIDER_KEYS = {
	[GATEWAY_PROVIDER.ALIPAY]: [UPSTREAM_PROVIDER_KEY.ALIPAY, UPSTREAM_PROVIDER_KEY.ALIPAY_DIRECT],
	[GATEWAY_PROVIDER.WXPAY]: [UPSTREAM_PROVIDER_KEY.WXPAY, UPSTREAM_PROVIDER_KEY.WXPAY_DIRECT],
	[GATEWAY_PROVIDER.STRIPE]: [UPSTREAM_PROVIDER_KEY.STRIPE],
} satisfies Record<Exclude<GatewayProvider, 'xunhupay' | 'generic'>, string[]>;

export const LOCAL_GATEWAY_HOSTS: ReadonlySet<string> = new Set(['localhost', '127.0.0.1', '[::1]']);
export const LOCAL_GENERIC_PROVIDER_BASE_URL = 'http://localhost';
