CREATE TABLE IF NOT EXISTS apps (id TEXT PRIMARY KEY NOT NULL, code TEXT NOT NULL UNIQUE, name TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'active', created_at INTEGER NOT NULL, updated_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS app_configs (app_id TEXT PRIMARY KEY NOT NULL, enabled_payment_types TEXT NOT NULL DEFAULT 'alipay,wxpay,stripe', min_amount INTEGER NOT NULL DEFAULT 100, max_amount INTEGER NOT NULL DEFAULT 100000, daily_limit INTEGER NOT NULL DEFAULT 1000000, order_timeout_minutes INTEGER NOT NULL DEFAULT 5, max_pending_orders INTEGER NOT NULL DEFAULT 3, balance_disabled INTEGER NOT NULL DEFAULT 0, help_text TEXT, help_image_url TEXT, updated_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS channels (id TEXT PRIMARY KEY NOT NULL, app_id TEXT NOT NULL, group_id INTEGER, name TEXT NOT NULL, platform TEXT NOT NULL DEFAULT 'generic', rate_multiplier INTEGER NOT NULL DEFAULT 10000, description TEXT, models TEXT, features TEXT, sort_order INTEGER NOT NULL DEFAULT 0, enabled INTEGER NOT NULL DEFAULT 1, created_at INTEGER NOT NULL, updated_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS subscription_plans (id TEXT PRIMARY KEY NOT NULL, app_id TEXT NOT NULL, group_id INTEGER, name TEXT NOT NULL, description TEXT, price INTEGER NOT NULL, original_price INTEGER, validity_days INTEGER NOT NULL DEFAULT 30, validity_unit TEXT NOT NULL DEFAULT 'day', features TEXT, product_name TEXT, for_sale INTEGER NOT NULL DEFAULT 0, sort_order INTEGER NOT NULL DEFAULT 0, created_at INTEGER NOT NULL, updated_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS orders (id TEXT PRIMARY KEY NOT NULL, app_id TEXT NOT NULL, user_id TEXT NOT NULL, user_email TEXT, amount INTEGER NOT NULL, pay_amount INTEGER NOT NULL, fee_rate INTEGER NOT NULL DEFAULT 0, recharge_code TEXT NOT NULL UNIQUE, status TEXT NOT NULL DEFAULT 'PENDING', payment_type TEXT NOT NULL, payment_trade_no TEXT, pay_url TEXT, qr_code TEXT, order_type TEXT NOT NULL DEFAULT 'balance', plan_id TEXT, expires_at INTEGER NOT NULL, paid_at INTEGER, completed_at INTEGER, failed_reason TEXT, client_ip TEXT, src_host TEXT, src_url TEXT, created_at INTEGER NOT NULL, updated_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS audit_logs (id TEXT PRIMARY KEY NOT NULL, order_id TEXT NOT NULL, action TEXT NOT NULL, detail TEXT, operator TEXT, created_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS payment_provider_instances (id TEXT PRIMARY KEY NOT NULL, app_id TEXT NOT NULL, provider_key TEXT NOT NULL, name TEXT NOT NULL, config TEXT NOT NULL DEFAULT '{}', supported_types TEXT NOT NULL DEFAULT '', enabled INTEGER NOT NULL DEFAULT 1, sort_order INTEGER NOT NULL DEFAULT 0, limits TEXT, refund_enabled INTEGER NOT NULL DEFAULT 0, created_at INTEGER NOT NULL, updated_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS system_configs (key TEXT PRIMARY KEY NOT NULL, value TEXT NOT NULL, "group" TEXT NOT NULL DEFAULT 'general', label TEXT, updated_at INTEGER NOT NULL);
CREATE INDEX IF NOT EXISTS orders_status_idx ON orders(status); CREATE INDEX IF NOT EXISTS orders_user_idx ON orders(user_id); CREATE INDEX IF NOT EXISTS channels_app_idx ON channels(app_id); CREATE INDEX IF NOT EXISTS plans_app_idx ON subscription_plans(app_id);
